'use client'

import { motion } from 'framer-motion'
import { Brain, Sparkles, FileText, Globe2, TrendingUp, Crosshair } from 'lucide-react'

const BRIEFING_TYPES = [
  { icon: Globe2, label: 'World Daily Briefing', desc: 'Top 10 global developments across all domains' },
  { icon: FileText, label: 'Country Briefing', desc: 'Deep profile: security, economy, weather, transport' },
  { icon: Crosshair, label: 'Conflict Analysis', desc: 'Parties, scope, timeline, implications' },
  { icon: TrendingUp, label: 'Market Intelligence', desc: 'FX signals, geopolitical impact on assets' },
  { icon: Globe2, label: 'Regional Risk Brief', desc: 'Comprehensive regional situational analysis' },
  { icon: Sparkles, label: 'Watchlist Briefing', desc: 'Personalized brief on your saved items' },
]

const SAMPLE_BRIEFING = `**Sudan Civil War — Situational Assessment**

The conflict between the Sudanese Armed Forces (SAF) and Rapid Support Forces (RSF) has entered a critical phase. RSF control of Khartoum's civilian districts is generating one of the fastest-growing humanitarian crises globally.

**Why this matters**
- 8.6M displaced — largest internal displacement crisis globally
- Red Sea logistics implications from instability in port access
- Uranium mining region affected — commodity supply risk
- Proxy dynamics: UAE-RSF / Egypt-SAF tensions complicate resolution

**Risk trajectory: DETERIORATING**`

export function LandingAI() {
  return (
    <section className="py-24 px-6">
      <div className="max-w-7xl mx-auto">
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          {/* Left: content */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 text-xs font-mono text-[var(--obs-purple)] tracking-widest uppercase mb-4">
              <div className="w-8 h-px bg-[var(--obs-purple)]" />
              AI INTELLIGENCE
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
              Not just data.{' '}
              <span className="text-[var(--obs-purple)]">Intelligence.</span>
            </h2>
            <p className="text-muted-foreground leading-relaxed mb-8">
              OBSERVE's AI layer uses GPT-4 to synthesize complex global events
              into clear, structured briefings. Understand not just what happened,
              but why it matters and what it means.
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {BRIEFING_TYPES.map((type) => (
                <div
                  key={type.label}
                  className="flex items-start gap-3 glass rounded-lg p-3 border border-white/5"
                >
                  <div className="w-7 h-7 rounded-md bg-[var(--obs-purple)]/15 border border-[var(--obs-purple)]/25 flex items-center justify-center flex-shrink-0">
                    <type.icon className="w-3.5 h-3.5 text-[var(--obs-purple)]" />
                  </div>
                  <div>
                    <div className="text-xs font-medium text-foreground">{type.label}</div>
                    <div className="text-xs text-muted-foreground">{type.desc}</div>
                  </div>
                </div>
              ))}
            </div>
          </motion.div>

          {/* Right: sample briefing card */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.2 }}
            className="relative"
          >
            {/* Glow */}
            <div className="absolute inset-0 bg-[var(--obs-purple)]/5 blur-3xl rounded-2xl" />

            <div className="relative glass-elevated rounded-2xl border border-[var(--obs-purple)]/20 overflow-hidden">
              {/* Header */}
              <div className="px-5 py-4 border-b border-white/5 flex items-center gap-3">
                <div className="w-7 h-7 rounded-md bg-[var(--obs-purple)]/20 border border-[var(--obs-purple)]/30 flex items-center justify-center">
                  <Brain className="w-4 h-4 text-[var(--obs-purple)]" />
                </div>
                <div>
                  <div className="text-sm font-medium">AI Conflict Briefing</div>
                  <div className="text-xs text-muted-foreground font-mono">Generated by GPT-4o · Just now</div>
                </div>
                <div className="ml-auto flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-[var(--obs-purple)] animate-pulse" />
                  <span className="text-xs text-[var(--obs-purple)] font-mono">LIVE</span>
                </div>
              </div>

              {/* Content */}
              <div className="p-5">
                <StreamingBriefing text={SAMPLE_BRIEFING} />
              </div>

              {/* Metadata */}
              <div className="px-5 py-3 border-t border-white/5 flex items-center gap-4 text-xs text-muted-foreground font-mono">
                <span>CONFLICT · SUDAN · HIGH SEVERITY</span>
                <span className="ml-auto">2 source events · 847 tokens</span>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}

// Simple typewriter effect for demo
function StreamingBriefing({ text }: { text: string }) {
  const lines = text.split('\n').filter(Boolean)

  return (
    <div className="space-y-3 text-sm">
      {lines.map((line, i) => {
        if (line.startsWith('**') && line.endsWith('**')) {
          return (
            <motion.div
              key={i}
              initial={{ opacity: 0 }}
              whileInView={{ opacity: 1 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.15 }}
              className="font-semibold text-foreground"
            >
              {line.replace(/\*\*/g, '')}
            </motion.div>
          )
        }
        if (line.startsWith('- ')) {
          return (
            <motion.div
              key={i}
              initial={{ opacity: 0, x: -4 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.12 }}
              className="flex items-start gap-2 text-muted-foreground"
            >
              <span className="text-[var(--obs-purple)] mt-1.5 flex-shrink-0">›</span>
              <span>{line.replace('- ', '')}</span>
            </motion.div>
          )
        }
        return (
          <motion.p
            key={i}
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.1 }}
            className="text-muted-foreground leading-relaxed"
          >
            {line}
          </motion.p>
        )
      })}
    </div>
  )
}
