// Country centroids — approximate geographic/political center of each country
// Used to draw relationship arc lines from event locations to involved parties

export interface CountryCentroid {
  name: string
  lat: number
  lng: number
}

// ISO 3166-1 alpha-2 → centroid
export const COUNTRY_CENTROIDS: Record<string, CountryCentroid> = {
  AD: { name: 'Andorra',             lat: 42.55, lng: 1.60  },
  AE: { name: 'UAE',                 lat: 24.47, lng: 54.37 },
  AF: { name: 'Afghanistan',         lat: 33.94, lng: 67.71 },
  AG: { name: 'Antigua & Barbuda',   lat: 17.07, lng: -61.80},
  AL: { name: 'Albania',             lat: 41.33, lng: 19.82 },
  AM: { name: 'Armenia',             lat: 40.18, lng: 44.51 },
  AO: { name: 'Angola',              lat: -8.84, lng: 13.23 },
  AR: { name: 'Argentina',           lat: -34.60,lng: -58.38},
  AT: { name: 'Austria',             lat: 47.81, lng: 13.03 },
  AU: { name: 'Australia',           lat: -35.28,lng: 149.13},
  AZ: { name: 'Azerbaijan',          lat: 40.41, lng: 49.87 },
  BA: { name: 'Bosnia',              lat: 43.85, lng: 18.39 },
  BB: { name: 'Barbados',            lat: 13.10, lng: -59.62},
  BD: { name: 'Bangladesh',          lat: 23.72, lng: 90.41 },
  BE: { name: 'Belgium',             lat: 50.85, lng: 4.35  },
  BF: { name: 'Burkina Faso',        lat: 12.36, lng: -1.53 },
  BG: { name: 'Bulgaria',            lat: 42.70, lng: 23.32 },
  BH: { name: 'Bahrain',             lat: 26.21, lng: 50.59 },
  BI: { name: 'Burundi',             lat: -3.38, lng: 29.36 },
  BJ: { name: 'Benin',               lat: 6.37,  lng: 2.43  },
  BN: { name: 'Brunei',              lat: 4.94,  lng: 114.95},
  BO: { name: 'Bolivia',             lat: -16.50,lng: -68.15},
  BR: { name: 'Brazil',              lat: -15.78,lng: -47.93},
  BS: { name: 'Bahamas',             lat: 25.08, lng: -77.35},
  BT: { name: 'Bhutan',              lat: 27.47, lng: 89.64 },
  BW: { name: 'Botswana',            lat: -24.65,lng: 25.91 },
  BY: { name: 'Belarus',             lat: 53.90, lng: 27.56 },
  BZ: { name: 'Belize',              lat: 17.25, lng: -88.77},
  CA: { name: 'Canada',              lat: 45.42, lng: -75.70},
  CD: { name: 'DR Congo',            lat: -4.32, lng: 15.32 },
  CF: { name: 'Central African Rep.', lat: 4.36, lng: 18.55 },
  CG: { name: 'Congo',               lat: -4.27, lng: 15.27 },
  CH: { name: 'Switzerland',         lat: 46.95, lng: 7.45  },
  CI: { name: "Côte d'Ivoire",       lat: 5.35,  lng: -4.00 },
  CL: { name: 'Chile',               lat: -33.46,lng: -70.65},
  CM: { name: 'Cameroon',            lat: 3.87,  lng: 11.52 },
  CN: { name: 'China',               lat: 39.91, lng: 116.39},
  CO: { name: 'Colombia',            lat: 4.71,  lng: -74.07},
  CR: { name: 'Costa Rica',          lat: 9.93,  lng: -84.08},
  CU: { name: 'Cuba',                lat: 23.13, lng: -82.38},
  CV: { name: 'Cape Verde',          lat: 14.93, lng: -23.51},
  CY: { name: 'Cyprus',              lat: 35.17, lng: 33.37 },
  CZ: { name: 'Czech Republic',      lat: 50.08, lng: 14.44 },
  DE: { name: 'Germany',             lat: 52.52, lng: 13.40 },
  DJ: { name: 'Djibouti',            lat: 11.59, lng: 43.15 },
  DK: { name: 'Denmark',             lat: 55.68, lng: 12.57 },
  DM: { name: 'Dominica',            lat: 15.30, lng: -61.39},
  DO: { name: 'Dominican Republic',  lat: 18.48, lng: -69.90},
  DZ: { name: 'Algeria',             lat: 36.74, lng: 3.06  },
  EC: { name: 'Ecuador',             lat: -0.23, lng: -78.52},
  EE: { name: 'Estonia',             lat: 59.44, lng: 24.75 },
  EG: { name: 'Egypt',               lat: 30.06, lng: 31.25 },
  EH: { name: 'Western Sahara',      lat: 24.22, lng: -12.89},
  ER: { name: 'Eritrea',             lat: 15.34, lng: 38.93 },
  ES: { name: 'Spain',               lat: 40.42, lng: -3.70 },
  ET: { name: 'Ethiopia',            lat: 9.03,  lng: 38.74 },
  FI: { name: 'Finland',             lat: 60.17, lng: 24.94 },
  FJ: { name: 'Fiji',                lat: -18.14,lng: 178.44},
  FR: { name: 'France',              lat: 48.86, lng: 2.35  },
  GA: { name: 'Gabon',               lat: 0.39,  lng: 9.45  },
  GB: { name: 'United Kingdom',      lat: 51.51, lng: -0.13 },
  GE: { name: 'Georgia',             lat: 41.69, lng: 44.83 },
  GH: { name: 'Ghana',               lat: 5.56,  lng: -0.20 },
  GM: { name: 'Gambia',              lat: 13.45, lng: -16.58},
  GN: { name: 'Guinea',              lat: 9.54,  lng: -13.68},
  GQ: { name: 'Eq. Guinea',          lat: 3.75,  lng: 8.78  },
  GR: { name: 'Greece',              lat: 37.98, lng: 23.73 },
  GT: { name: 'Guatemala',           lat: 14.64, lng: -90.51},
  GW: { name: 'Guinea-Bissau',       lat: 11.86, lng: -15.60},
  GY: { name: 'Guyana',              lat: 6.80,  lng: -58.16},
  HN: { name: 'Honduras',            lat: 14.10, lng: -87.21},
  HR: { name: 'Croatia',             lat: 45.81, lng: 15.98 },
  HT: { name: 'Haiti',               lat: 18.54, lng: -72.34},
  HU: { name: 'Hungary',             lat: 47.50, lng: 19.04 },
  ID: { name: 'Indonesia',           lat: -6.21, lng: 106.85},
  IE: { name: 'Ireland',             lat: 53.33, lng: -6.25 },
  IL: { name: 'Israel',              lat: 31.77, lng: 35.22 },
  IN: { name: 'India',               lat: 28.61, lng: 77.21 },
  IQ: { name: 'Iraq',                lat: 33.34, lng: 44.40 },
  IR: { name: 'Iran',                lat: 35.69, lng: 51.42 },
  IS: { name: 'Iceland',             lat: 64.13, lng: -21.90},
  IT: { name: 'Italy',               lat: 41.90, lng: 12.48 },
  JM: { name: 'Jamaica',             lat: 17.99, lng: -76.79},
  JO: { name: 'Jordan',              lat: 31.95, lng: 35.93 },
  JP: { name: 'Japan',               lat: 35.69, lng: 139.69},
  KE: { name: 'Kenya',               lat: -1.29, lng: 36.82 },
  KG: { name: 'Kyrgyzstan',          lat: 42.87, lng: 74.59 },
  KH: { name: 'Cambodia',            lat: 11.56, lng: 104.92},
  KI: { name: 'Kiribati',            lat: 1.33,  lng: 173.00},
  KM: { name: 'Comoros',             lat: -11.70,lng: 43.26 },
  KP: { name: 'North Korea',         lat: 39.02, lng: 125.75},
  KR: { name: 'South Korea',         lat: 37.57, lng: 126.98},
  KW: { name: 'Kuwait',              lat: 29.37, lng: 47.98 },
  KZ: { name: 'Kazakhstan',          lat: 51.18, lng: 71.45 },
  LA: { name: 'Laos',                lat: 17.97, lng: 102.60},
  LB: { name: 'Lebanon',             lat: 33.89, lng: 35.50 },
  LI: { name: 'Liechtenstein',       lat: 47.14, lng: 9.52  },
  LK: { name: 'Sri Lanka',           lat: 6.93,  lng: 79.85 },
  LR: { name: 'Liberia',             lat: 6.30,  lng: -10.80},
  LS: { name: 'Lesotho',             lat: -29.32,lng: 27.48 },
  LT: { name: 'Lithuania',           lat: 54.69, lng: 25.28 },
  LU: { name: 'Luxembourg',          lat: 49.61, lng: 6.13  },
  LV: { name: 'Latvia',              lat: 56.95, lng: 24.11 },
  LY: { name: 'Libya',               lat: 32.90, lng: 13.18 },
  MA: { name: 'Morocco',             lat: 34.02, lng: -6.85 },
  MC: { name: 'Monaco',              lat: 43.73, lng: 7.42  },
  MD: { name: 'Moldova',             lat: 47.00, lng: 28.86 },
  ME: { name: 'Montenegro',          lat: 42.44, lng: 19.26 },
  MG: { name: 'Madagascar',          lat: -18.91,lng: 47.54 },
  MK: { name: 'North Macedonia',     lat: 42.00, lng: 21.43 },
  ML: { name: 'Mali',                lat: 12.65, lng: -8.00 },
  MM: { name: 'Myanmar',             lat: 16.87, lng: 96.19 },
  MN: { name: 'Mongolia',            lat: 47.91, lng: 106.92},
  MR: { name: 'Mauritania',          lat: 18.08, lng: -15.97},
  MT: { name: 'Malta',               lat: 35.90, lng: 14.51 },
  MU: { name: 'Mauritius',           lat: -20.16,lng: 57.50 },
  MV: { name: 'Maldives',            lat: 4.18,  lng: 73.51 },
  MW: { name: 'Malawi',              lat: -13.97,lng: 33.79 },
  MX: { name: 'Mexico',              lat: 19.43, lng: -99.13},
  MY: { name: 'Malaysia',            lat: 3.15,  lng: 101.69},
  MZ: { name: 'Mozambique',          lat: -25.97,lng: 32.59 },
  NA: { name: 'Namibia',             lat: -22.56,lng: 17.08 },
  NE: { name: 'Niger',               lat: 13.51, lng: 2.11  },
  NG: { name: 'Nigeria',             lat: 9.07,  lng: 7.40  },
  NI: { name: 'Nicaragua',           lat: 12.13, lng: -86.30},
  NL: { name: 'Netherlands',         lat: 52.37, lng: 4.90  },
  NO: { name: 'Norway',              lat: 59.91, lng: 10.75 },
  NP: { name: 'Nepal',               lat: 27.71, lng: 85.32 },
  NR: { name: 'Nauru',               lat: -0.53, lng: 166.92},
  NZ: { name: 'New Zealand',         lat: -41.29,lng: 174.78},
  OM: { name: 'Oman',                lat: 23.61, lng: 58.59 },
  PA: { name: 'Panama',              lat: 8.99,  lng: -79.52},
  PE: { name: 'Peru',                lat: -12.05,lng: -77.04},
  PG: { name: 'Papua New Guinea',    lat: -9.44, lng: 147.19},
  PH: { name: 'Philippines',         lat: 14.60, lng: 120.98},
  PK: { name: 'Pakistan',            lat: 33.72, lng: 73.06 },
  PL: { name: 'Poland',              lat: 52.23, lng: 21.01 },
  PT: { name: 'Portugal',            lat: 38.72, lng: -9.14 },
  PW: { name: 'Palau',               lat: 7.50,  lng: 134.62},
  PY: { name: 'Paraguay',            lat: -25.28,lng: -57.64},
  QA: { name: 'Qatar',               lat: 25.29, lng: 51.53 },
  RO: { name: 'Romania',             lat: 44.44, lng: 26.10 },
  RS: { name: 'Serbia',              lat: 44.80, lng: 20.46 },
  RU: { name: 'Russia',              lat: 55.75, lng: 37.62 },
  RW: { name: 'Rwanda',              lat: -1.95, lng: 30.06 },
  SA: { name: 'Saudi Arabia',        lat: 24.69, lng: 46.72 },
  SB: { name: 'Solomon Islands',     lat: -9.43, lng: 160.03},
  SC: { name: 'Seychelles',          lat: -4.62, lng: 55.45 },
  SD: { name: 'Sudan',               lat: 15.56, lng: 32.53 },
  SE: { name: 'Sweden',              lat: 59.33, lng: 18.07 },
  SG: { name: 'Singapore',           lat: 1.35,  lng: 103.82},
  SI: { name: 'Slovenia',            lat: 46.05, lng: 14.51 },
  SK: { name: 'Slovakia',            lat: 48.15, lng: 17.11 },
  SL: { name: 'Sierra Leone',        lat: 8.49,  lng: -13.23},
  SM: { name: 'San Marino',          lat: 43.94, lng: 12.46 },
  SN: { name: 'Senegal',             lat: 14.69, lng: -17.44},
  SO: { name: 'Somalia',             lat: 2.05,  lng: 45.34 },
  SR: { name: 'Suriname',            lat: 5.87,  lng: -55.17},
  SS: { name: 'South Sudan',         lat: 4.86,  lng: 31.60 },
  ST: { name: 'São Tomé & Príncipe', lat: 0.34,  lng: 6.73  },
  SV: { name: 'El Salvador',         lat: 13.69, lng: -89.19},
  SY: { name: 'Syria',               lat: 33.51, lng: 36.29 },
  SZ: { name: 'Eswatini',            lat: -26.32,lng: 31.14 },
  TD: { name: 'Chad',                lat: 12.11, lng: 15.04 },
  TG: { name: 'Togo',                lat: 6.14,  lng: 1.22  },
  TH: { name: 'Thailand',            lat: 13.75, lng: 100.52},
  TJ: { name: 'Tajikistan',          lat: 38.56, lng: 68.77 },
  TL: { name: 'Timor-Leste',         lat: -8.56, lng: 125.59},
  TM: { name: 'Turkmenistan',        lat: 37.95, lng: 58.38 },
  TN: { name: 'Tunisia',             lat: 36.82, lng: 10.18 },
  TO: { name: 'Tonga',               lat: -21.13,lng: -175.22},
  TR: { name: 'Turkey',              lat: 39.93, lng: 32.86 },
  TT: { name: 'Trinidad & Tobago',   lat: 10.65, lng: -61.52},
  TV: { name: 'Tuvalu',              lat: -8.52, lng: 179.20},
  TZ: { name: 'Tanzania',            lat: -6.17, lng: 35.74 },
  UA: { name: 'Ukraine',             lat: 50.45, lng: 30.52 },
  UG: { name: 'Uganda',              lat: 0.32,  lng: 32.58 },
  US: { name: 'United States',       lat: 38.89, lng: -77.04},
  UY: { name: 'Uruguay',             lat: -34.90,lng: -56.19},
  UZ: { name: 'Uzbekistan',          lat: 41.30, lng: 69.24 },
  VA: { name: 'Vatican City',        lat: 41.90, lng: 12.45 },
  VC: { name: 'St. Vincent',         lat: 13.16, lng: -61.22},
  VE: { name: 'Venezuela',           lat: 10.48, lng: -66.88},
  VN: { name: 'Vietnam',             lat: 21.03, lng: 105.85},
  VU: { name: 'Vanuatu',             lat: -17.73,lng: 168.32},
  WS: { name: 'Samoa',               lat: -13.82,lng: -172.14},
  YE: { name: 'Yemen',               lat: 15.35, lng: 44.21 },
  ZA: { name: 'South Africa',        lat: -25.75,lng: 28.19 },
  ZM: { name: 'Zambia',              lat: -15.42,lng: 28.28 },
  ZW: { name: 'Zimbabwe',            lat: -17.83,lng: 31.05 },

  // Non-standard but commonly used in tags/events
  PS: { name: 'Palestine',           lat: 31.90, lng: 35.20 },
  TW: { name: 'Taiwan',              lat: 25.05, lng: 121.53},
  XK: { name: 'Kosovo',              lat: 42.67, lng: 21.17 },
  HK: { name: 'Hong Kong',           lat: 22.32, lng: 114.17},
}

// Common name / alias → ISO code lookup (case-insensitive match)
const NAME_ALIASES: Record<string, string> = {
  // Major geopolitical actors
  'russia':                   'RU', 'russian federation':     'RU', 'kremlin':             'RU',
  'ukraine':                  'UA', 'ukrainian forces':       'UA', 'kyiv':                'UA',
  'united states':            'US', 'usa':                    'US', 'america':             'US',
  'united states of america': 'US', 'pentagon':               'US', 'washington':          'US',
  'china':                    'CN', "people's republic of china": 'CN', 'prc':              'CN', 'beijing': 'CN',
  'israel':                   'IL', 'idf':                    'IL', 'israel defense forces': 'IL',
  'iran':                     'IR', 'islamic republic':       'IR', 'tehran':              'IR', 'irgc': 'IR',
  'saudi arabia':             'SA', 'ksa':                    'SA', 'riyadh':              'SA',
  'pakistan':                 'PK', 'islamabad':              'PK',
  'india':                    'IN', 'new delhi':              'IN',
  'north korea':              'KP', 'dprk':                   'KP', 'pyongyang':           'KP',
  'south korea':              'KR', 'seoul':                  'KR',
  'japan':                    'JP', 'tokyo':                  'JP',
  'turkey':                   'TR', 'turkiye':                'TR', 'ankara':              'TR',
  'germany':                  'DE', 'berlin':                 'DE',
  'france':                   'FR', 'paris':                  'FR',
  'united kingdom':           'GB', 'uk':                     'GB', 'britain':             'GB', 'london': 'GB', 'nato ally': 'GB',
  'nato':                     'BE', // Brussels-based
  'eu':                       'BE', 'european union':         'BE',
  'brazil':                   'BR', 'brasilia':               'BR',
  'mexico':                   'MX', 'mexico city':            'MX',
  'nigeria':                  'NG', 'abuja':                  'NG',
  'ethiopia':                 'ET', 'addis ababa':            'ET',
  'egypt':                    'EG', 'cairo':                  'EG',
  'iraq':                     'IQ', 'baghdad':                'IQ',
  'syria':                    'SY', 'damascus':               'SY', 'syrian government':   'SY',
  'yemen':                    'YE', 'sanaa':                  'YE', 'houthis':             'YE', 'houthi': 'YE',
  'libya':                    'LY', 'tripoli':                'LY',
  'sudan':                    'SD', 'khartoum':               'SD',
  'somalia':                  'SO', 'mogadishu':              'SO', 'al-shabaab':          'SO',
  'myanmar':                  'MM', 'burma':                  'MM', 'naypyidaw':           'MM',
  'afghanistan':              'AF', 'kabul':                  'AF', 'taliban':             'AF',
  'venezuela':                'VE', 'caracas':                'VE',
  'colombia':                 'CO', 'bogota':                 'CO', 'farc':                'CO',
  'gaza':                     'PS', 'west bank':              'PS', 'hamas':               'PS', 'plo': 'PS',
  'taiwan':                   'TW', 'taipei':                 'TW',
  'belarus':                  'BY', 'minsk':                  'BY',
  'azerbaijan':               'AZ', 'baku':                   'AZ',
  'armenia':                  'AM', 'yerevan':                'AM',
  'georgia':                  'GE', 'tbilisi':                'GE',
  'moldova':                  'MD', 'chisinau':               'MD',
  'hezbollah':                'LB', 'lebanese':               'LB', 'lebanon':             'LB',
  'mali':                     'ML', 'bamako':                 'ML',
  'niger':                    'NE', 'niamey':                 'NE',
  'burkina faso':             'BF', 'ouagadougou':            'BF',
  'indonesia':                'ID', 'jakarta':                'ID',
  'philippines':              'PH', 'manila':                 'PH',
  'vietnam':                  'VN', 'hanoi':                  'VN',
  'south africa':             'ZA', 'pretoria':               'ZA',
}

/**
 * Look up a country centroid by ISO code OR common name/alias.
 */
export function lookupCountry(nameOrCode: string): CountryCentroid | null {
  const upper = nameOrCode.trim().toUpperCase()
  // Try exact ISO code first
  if (COUNTRY_CENTROIDS[upper]) return COUNTRY_CENTROIDS[upper]

  // Try name alias (case-insensitive)
  const lower = nameOrCode.trim().toLowerCase()
  const isoFromName = NAME_ALIASES[lower]
  if (isoFromName) return COUNTRY_CENTROIDS[isoFromName] ?? null

  // Partial name match against centroid names
  const keys = Object.keys(COUNTRY_CENTROIDS)
  for (const k of keys) {
    if (COUNTRY_CENTROIDS[k].name.toLowerCase() === lower) return COUNTRY_CENTROIDS[k]
  }

  return null
}
