import type { LayerConfig } from '@/types/map'

// Master layer registry — defines all 15 intelligence layers
export const LAYER_CONFIGS: LayerConfig[] = [
  {
    id: 'conflicts',
    label: 'Conflicts & Wars',
    category: 'security',
    icon: 'Sword',
    color: '#ef4444',
    description: 'Active armed conflicts, civil unrest, border tensions, territorial disputes',
    eventType: 'conflict',
    defaultVisible: true,
    requiresAuth: false,
  },
  {
    id: 'news',
    label: 'Breaking News',
    category: 'news',
    icon: 'Newspaper',
    color: '#f97316',
    description: 'Geolocated global news with AI-generated summaries',
    eventType: 'news',
    defaultVisible: true,
    requiresAuth: false,
  },
  {
    id: 'weather',
    label: 'Weather & Storms',
    category: 'environment',
    icon: 'CloudLightning',
    color: '#3b82f6',
    description: 'Tropical storms, severe weather, active alerts',
    eventType: 'weather',
    defaultVisible: true,
    requiresAuth: false,
  },
  {
    id: 'disasters',
    label: 'Natural Disasters',
    category: 'environment',
    icon: 'AlertTriangle',
    color: '#f59e0b',
    description: 'Earthquakes, tsunamis, wildfires, floods, volcanic activity',
    eventType: 'weather',
    defaultVisible: true,
    requiresAuth: false,
  },
  {
    id: 'flights',
    label: 'Air Traffic',
    category: 'transport',
    icon: 'Plane',
    color: '#22d3ee',
    description: 'Live flight positions from public ADS-B data',
    eventType: 'flight',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'shipping',
    label: 'Maritime Activity',
    category: 'transport',
    icon: 'Ship',
    color: '#06b6d4',
    description: 'Vessel positions, shipping lanes, port congestion',
    eventType: 'vessel',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'markets',
    label: 'Market Signals',
    category: 'markets',
    icon: 'TrendingUp',
    color: '#eab308',
    description: 'FX volatility, crypto signals, macro events affecting markets',
    eventType: 'market',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'country_risk',
    label: 'Country Risk',
    category: 'intelligence',
    icon: 'Globe2',
    color: '#8b5cf6',
    description: 'Country-level risk score overlays across all nations',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'political',
    label: 'Political Events',
    category: 'security',
    icon: 'Activity',
    color: '#a78bfa',
    description: 'Elections, protests, regime changes, diplomatic incidents',
    eventType: 'political',
    defaultVisible: false,
    requiresAuth: false,
  },
  {
    id: 'sanctions',
    label: 'Sanctions & Regulation',
    category: 'markets',
    icon: 'Shield',
    color: '#f59e0b',
    description: 'New sanctions regimes, regulatory changes, compliance events',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'energy',
    label: 'Energy & Resources',
    category: 'markets',
    icon: 'Zap',
    color: '#10b981',
    description: 'Pipeline disruptions, energy infrastructure, resource conflicts',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'tensions',
    label: 'Tensions & Hotspots',
    category: 'security',
    icon: 'Crosshair',
    color: '#fb923c',
    description: 'Regional tension zones, military exercises, escalation indicators',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'infrastructure',
    label: 'Infrastructure',
    category: 'transport',
    icon: 'Network',
    color: '#94a3b8',
    description: 'Port closures, airport disruptions, critical infrastructure events',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'alerts',
    label: 'My Alerts',
    category: 'intelligence',
    icon: 'BellRing',
    color: '#d946ef',
    description: 'Your custom alert triggers shown on the map',
    defaultVisible: false,
    requiresAuth: true,
  },
  {
    id: 'watchlist',
    label: 'Watchlist',
    category: 'intelligence',
    icon: 'Bookmark',
    color: '#4ade80',
    description: 'Highlight your watched countries, assets, and regions',
    defaultVisible: false,
    requiresAuth: true,
  },
]

export const LAYER_BY_ID = Object.fromEntries(
  LAYER_CONFIGS.map((l) => [l.id, l])
) as Record<string, LayerConfig>

export const LAYER_CATEGORIES = {
  security: LAYER_CONFIGS.filter((l) => l.category === 'security'),
  news: LAYER_CONFIGS.filter((l) => l.category === 'news'),
  environment: LAYER_CONFIGS.filter((l) => l.category === 'environment'),
  transport: LAYER_CONFIGS.filter((l) => l.category === 'transport'),
  markets: LAYER_CONFIGS.filter((l) => l.category === 'markets'),
  intelligence: LAYER_CONFIGS.filter((l) => l.category === 'intelligence'),
}
