import { Metadata } from 'next'
import Link from 'next/link'
import { Globe, Map, Newspaper, Cloud, TrendingUp, Navigation, Zap, Bell, BookOpen, Settings, Key, ChevronRight } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Documentation',
  description: 'Learn how to use OBSERVE — the global intelligence platform.',
}

function NavHeader() {
  return (
    <header className="border-b border-border/30 px-6 py-4">
      <div className="max-w-4xl mx-auto flex items-center justify-between">
        <Link href="/" className="inline-flex items-center gap-2">
          <div className="w-6 h-6 rounded-md bg-[var(--obs-teal)] flex items-center justify-center">
            <Globe className="w-3.5 h-3.5 text-background" />
          </div>
          <span className="font-bold text-sm tracking-wider uppercase">OBSERVE</span>
        </Link>
        <div className="flex items-center gap-4 text-sm text-muted-foreground">
          <Link href="/data-sources" className="hover:text-foreground transition-colors">Data Sources</Link>
          <Link href="/api-reference" className="hover:text-foreground transition-colors">API Reference</Link>
          <Link href="/login" className="hover:text-foreground transition-colors">Sign in</Link>
        </div>
      </div>
    </header>
  )
}

const MODULES = [
  {
    icon: Map,
    title: 'World Map',
    color: 'var(--obs-teal)',
    description: 'Interactive globe showing all live events — earthquakes, weather, conflicts, flights, vessels, and news — as color-coded markers.',
    details: [
      'Click any marker to open the event detail panel.',
      'Use the layer toggles (top right) to show/hide event types.',
      'Zoom and pan freely; the map re-queries visible markers on move.',
      'Heatmap mode aggregates dense areas into intensity gradients.',
    ],
  },
  {
    icon: Newspaper,
    title: 'News Intelligence',
    color: 'var(--obs-amber)',
    description: 'Curated geopolitical news from the GDELT Project — English-language articles filtered for high-relevance global events.',
    details: [
      'Stories are scored by severity (Critical → Minimal) using keyword and topic signals.',
      'Filter by topic tag: geopolitics, economy, security, technology, disaster, sanctions, nuclear, elections.',
      'Search searches both title and summary.',
      'Connect your own NewsAPI key in Settings → Integrations for additional sources.',
    ],
  },
  {
    icon: Cloud,
    title: 'Weather & Disasters',
    color: 'var(--obs-blue)',
    description: 'Live severe weather alerts from NOAA/NWS (US) and significant earthquake data from USGS — rolling 7-day window.',
    details: [
      'NOAA covers Extreme and Severe alerts for US territories.',
      'USGS tracks all significant earthquakes globally (magnitude varies by significance).',
      'Events older than 7 days are automatically removed from the feed.',
      'Connect OpenWeatherMap in Settings for global city-level weather data.',
    ],
  },
  {
    icon: TrendingUp,
    title: 'Markets',
    color: 'var(--obs-amber)',
    description: 'Real-time cryptocurrency prices (BTC, ETH, SOL, XRP, ADA, DOT) and FX rates for 10 major currency pairs.',
    details: [
      'Crypto data from CoinCap — updated on every manual refresh.',
      'FX rates from ExchangeRate-API (USD base, 10 pairs).',
      'Price rows flash green/red when a value changes live.',
      'Market-related global events appear below the price table.',
    ],
  },
  {
    icon: Navigation,
    title: 'Transport',
    color: 'var(--obs-teal)',
    description: 'Flight and vessel tracking for Europe and the Middle East — updated when you connect an OpenSky Network account.',
    details: [
      'Requires your own OpenSky credentials — connect in Settings → Integrations.',
      'Flights tab shows airborne and grounded aircraft with callsign, altitude, speed, heading.',
      'Vessels tab shows cargo ships and tankers with MMSI, flag, destination.',
      'Data reflects a 7-day rolling window of tracked positions.',
    ],
  },
  {
    icon: Zap,
    title: 'Conflicts',
    color: 'var(--obs-red)',
    description: 'Armed conflict event tracking from ACLED — the leading academic conflict dataset.',
    details: [
      'Requires your own ACLED credentials — register free at acleddata.com then connect in Settings → Integrations.',
      'Shows event type (battle, explosion, protest), actors, fatalities, and location.',
      'ACLED data is updated weekly by their team; your account refreshes on cron.',
    ],
  },
  {
    icon: BookOpen,
    title: 'AI Briefings',
    color: 'var(--obs-purple)',
    description: 'On-demand intelligence briefings generated by Perplexity AI based on current platform data.',
    details: [
      'Requires your own Perplexity AI API key — get one at perplexity.ai then connect in Settings → Integrations.',
      'Briefings are generated fresh each time and take 10–30 seconds.',
      'Past briefings are saved to your account for reference.',
    ],
  },
  {
    icon: Bell,
    title: 'Alerts',
    color: 'var(--obs-green)',
    description: 'Custom alert rules that notify you when new events match your criteria.',
    details: [
      'Create rules by country, keyword, event type, or severity level.',
      'Alerts appear in the Alerts tab and (if enabled) via email.',
      'Combine multiple conditions with AND logic for precision.',
    ],
  },
]

export default function DocsPage() {
  return (
    <div className="min-h-screen bg-background">
      <NavHeader />

      <main className="max-w-4xl mx-auto px-6 py-12 space-y-12">
        {/* Header */}
        <div className="space-y-3">
          <h1 className="text-3xl font-bold text-foreground">Documentation</h1>
          <p className="text-muted-foreground leading-relaxed max-w-2xl">
            OBSERVE is a global intelligence platform that aggregates open-source data across
            geopolitics, weather, markets, transport, and news into a single real-time interface.
            This guide covers every module and how to get the most out of each one.
          </p>
        </div>

        {/* Quick start */}
        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground">Getting Started</h2>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            {[
              { step: '1', title: 'Subscribe', desc: 'Create your account and subscribe for $29/month at checkout.' },
              { step: '2', title: 'Explore the map', desc: 'The World Map is live immediately — no setup required.' },
              { step: '3', title: 'Connect your keys', desc: 'Go to Settings → Integrations to unlock News, Conflicts, AI Briefings, and Transport.' },
            ].map(s => (
              <div key={s.step} className="rounded-xl border border-border/30 p-5 space-y-2">
                <div className="w-7 h-7 rounded-full bg-[var(--obs-teal)]/15 border border-[var(--obs-teal)]/30 flex items-center justify-center text-xs font-bold text-[var(--obs-teal)]">
                  {s.step}
                </div>
                <div className="font-semibold text-sm text-foreground">{s.title}</div>
                <div className="text-xs text-muted-foreground leading-relaxed">{s.desc}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Platform modules */}
        <section className="space-y-6">
          <h2 className="text-xl font-semibold text-foreground">Platform Modules</h2>
          <div className="space-y-4">
            {MODULES.map(mod => (
              <div key={mod.title} className="rounded-xl border border-border/20 p-5 space-y-3">
                <div className="flex items-center gap-3">
                  <div
                    className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0"
                    style={{ background: `${mod.color}18`, border: `1px solid ${mod.color}30` }}
                  >
                    <mod.icon className="w-4 h-4" style={{ color: mod.color }} />
                  </div>
                  <h3 className="font-semibold text-foreground">{mod.title}</h3>
                </div>
                <p className="text-sm text-muted-foreground leading-relaxed">{mod.description}</p>
                <ul className="space-y-1.5">
                  {mod.details.map((d, i) => (
                    <li key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                      <ChevronRight className="w-3 h-3 mt-0.5 flex-shrink-0 text-muted-foreground/40" />
                      {d}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>

        {/* BYOK section */}
        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-foreground flex items-center gap-2">
            <Key className="w-5 h-5 text-[var(--obs-amber)]" />
            Bring Your Own Keys (BYOK)
          </h2>
          <p className="text-sm text-muted-foreground leading-relaxed">
            Several modules require you to connect a free API key from a third-party provider.
            Your keys are encrypted and stored only in your account — we never share or use them outside your sessions.
            Connect all integrations from <strong className="text-foreground">Settings → Integrations</strong>.
          </p>
          <div className="rounded-xl border border-[var(--obs-amber)]/20 bg-[var(--obs-amber)]/5 p-5">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-xs font-mono text-muted-foreground uppercase tracking-wider text-left">
                  <th className="pb-3">Module</th>
                  <th className="pb-3">Provider</th>
                  <th className="pb-3">Cost</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border/20">
                {[
                  { module: 'News Intelligence', provider: 'NewsAPI', url: 'newsapi.org', cost: 'Free (dev) / $449/mo commercial' },
                  { module: 'Conflicts', provider: 'ACLED', url: 'acleddata.com', cost: 'Free registration' },
                  { module: 'AI Briefings', provider: 'Perplexity AI', url: 'perplexity.ai', cost: 'Pay-as-you-go API' },
                  { module: 'Transport', provider: 'OpenSky Network', url: 'opensky-network.org', cost: 'Free registration' },
                  { module: 'Weather (global)', provider: 'OpenWeatherMap', url: 'openweathermap.org', cost: 'Free tier (1k calls/day)' },
                ].map(r => (
                  <tr key={r.module}>
                    <td className="py-2.5 pr-4 text-foreground/80 font-medium">{r.module}</td>
                    <td className="py-2.5 pr-4">
                      <a href={`https://${r.url}`} target="_blank" rel="noopener noreferrer"
                        className="text-[var(--obs-teal)] hover:underline">{r.provider}</a>
                    </td>
                    <td className="py-2.5 text-muted-foreground text-xs">{r.cost}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Settings */}
        <section className="space-y-3">
          <h2 className="text-xl font-semibold text-foreground flex items-center gap-2">
            <Settings className="w-5 h-5 text-muted-foreground" />
            Settings
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-sm">
            {[
              { tab: 'Profile', desc: 'Update your display name and email.' },
              { tab: 'Integrations', desc: 'Connect third-party API keys (NewsAPI, ACLED, Perplexity, OpenSky, OpenWeatherMap).' },
              { tab: 'Billing', desc: 'View your subscription status, upgrade, or open the Stripe billing portal to manage payment.' },
              { tab: 'Display', desc: 'Switch language (English / Spanish), adjust theme, and set your default region.' },
              { tab: 'Notifications', desc: 'Configure which alert types trigger email notifications.' },
            ].map(s => (
              <div key={s.tab} className="rounded-lg border border-border/20 px-4 py-3">
                <div className="font-medium text-foreground mb-0.5">{s.tab}</div>
                <div className="text-xs text-muted-foreground">{s.desc}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Footer nav */}
        <div className="border-t border-border/30 pt-8 flex flex-wrap gap-4 text-sm text-muted-foreground">
          <Link href="/" className="hover:text-foreground transition-colors">Home</Link>
          <Link href="/data-sources" className="hover:text-foreground transition-colors">Data Sources</Link>
          <Link href="/api-reference" className="hover:text-foreground transition-colors">API Reference</Link>
          <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
          <Link href="/tos" className="hover:text-foreground transition-colors">Terms of Service</Link>
        </div>
      </main>
    </div>
  )
}
